<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JoJoZ" failures="1" tests="8" name="com.orangehrm.com.orangehrm.Login" time="58.281" errors="0" timestamp="2025-05-15T20:13:43 IST" skipped="0">
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="OrangeHrmLoginBothInvalidCredentials" time="6.887"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="OrangeHrmLoginEmptyCredentials" time="5.502"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="ForgotPasswordwithValidUsername" time="8.181"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="OrangeHrmLoginValidCredentials" time="7.280"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="ForgotPasswordValidUsernameCheck" time="7.978">
    <failure message="❌ Bug: Reset password message shown for invalid username expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Bug: Reset password message shown for invalid username expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.orangehrm.com.orangehrm.Login.ForgotPasswordValidUsernameCheck(Login.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- ForgotPasswordValidUsernameCheck -->
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="OrangeHrmLoginInvalidPassword" time="8.576"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="OrangeHrmLoginInvalidUsername" time="6.747"/>
  <testcase classname="com.orangehrm.com.orangehrm.Login" name="ForgotPasswordCancelButton" time="7.130"/>
</testsuite> <!-- com.orangehrm.com.orangehrm.Login -->
